version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mythicalmysfits-questions-service-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1m8qnzobarz4q"
s3_prefix = "mythicalmysfits-questions-service-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
